name: Discord Notifications

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Push
        if: github.event_name == 'push'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"🚀 A new push to the repository: ${GITHUB_REPOSITORY}\nCommit: ${GITHUB_SHA}\nCheck it out: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Release
        if: github.event_name == 'release'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"🎉 A new release has been published: ${GITHUB_REPOSITORY}\nRelease: ${GITHUB_REF_NAME}\nCheck it out: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/latest\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Manual Trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"🛠 This workflow was triggered manually for: ${GITHUB_REPOSITORY}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
